baseURL = "https://jfreedman0212.github.io/"
languageCode = "en-us"
title = "Josh Freedman"
theme = "hugo-ink"
paginate = 3
copyright = "© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    subtitle = "My personal archive for code snippets and ramblings about software and life"
    mode = "light"
    featherIconsCDN = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/jfreedman0212"

[[params.social]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/jfreedman0212"

[taxonomies]
    tag = "tags"
